export enum EClientEventName {
    SESSION = "session",
    ERROR = "error",
    CALL_OFFER = "call.offer",
    CALL_OFFERED = "call.offered",
    CALL_HELD = "call.held",
    CALL_UNHELD = "call.unheld",
    CALL_TRANSFERRED = "call.transferred",
    CALL_MUTE = "call.mute",
    AGENT_STATE = "agent.state",
    RECONNECTED = "reconnected",
    CONTACT_CREATED = "contact.created",
    CONTACT_UPDATED = "contact.updated",
    CONTACT_DELETED = "contact.deleted",
    TEAM_ASSIGNED = "team.assigned",
    TEAM_UNASSIGNED = "team.unassigned",
}