export enum EMessageNotification {
    "CONNECT" = "session.connect",
    "PING" = "session.ping",
    "PONG" = "session.pong",
    "CALL_STATE" = "call.state",
    "CALL_OFFER" = "call.offer",
    "CALL_REJECT" = "call.reject",
    "CALL_HANGUP" = "call.hangup",
    "CALL_ANSWER" = "call.answer",
    "CALL_HOLD" = "call.hold",
    "CALL_UNHOLD" = "call.unhold",
    "CALL_TRANSFER" = "call.transfer",
    "CALL_DTMF" = "call.dtmf",
    "CALL_MUTE" = "call.mute",
    "CALL_RECONNECT" = "call.reconnect",
    "CALL_GET_OFFER" = "call.getOffer",
    "AGENT_STATE" = "agent.state",
}